apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-backend
  labels:
    app: stargate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stargate-backend
  template:
    metadata:
      labels:
        app: stargate-backend
    spec:
      containers:
      - name: stargate-backend
        image: stargate-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: STARGATE_STORAGE
          value: postgres
        - name: STARGATE_PG_DSN
          valueFrom:
            secretKeyRef:
              name: stargate-stack-secrets
              key: postgres-dsn
        - name: STARGATE_PROXY_BASE
          value: http://starlight-api:8080
        - name: BITCOIN_NETWORK
          value: testnet4
        - name: UPLOADS_DIR
          value: /data/uploads
        - name: BLOCKS_DIR
          value: /data/blocks
        - name: STARGATE_INGEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: stargate-stack-secrets
              key: ingest-token
        - name: STARGATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: stargate-stack-secrets
              key: api-key
        - name: STARGATE_SEED_FIXTURES
          value: "false"
        - name: STARLIGHT_DONATION_ADDRESS
          value: tb1qwykfvl6s0lmlkn8qzcrwv2y4nghycmgl0t4
        - name: STARLIGHT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: stargate-stack-secrets
              key: public-key