package agents

import (
	"context"
	"fmt"
	"html"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"time"
)

// ExecutionRequest describes a unit of work the worker wants performed.
type ExecutionRequest struct {
	ContractID        string
	VisiblePixelHash  string
	TaskID            string
	Title             string
	Description       string
	ProposalContext   string
	PreviousWork      string
	RejectionFeedback string
	Workdir           string // preferred absolute path (results/<hash>)
}

// ExecutionResult is the deliverable returned to be submitted.
type ExecutionResult struct {
	Notes             string
	ResultFile        string // public URL under /uploads/...
	ArtifactsDir      string
	CompletionProof   string
}

// Executor performs the actual "thinking + implementation" for a task.
// The built-in agent uses this to decouple orchestration from LLM execution.
//
// Implementations:
//   - StubExecutor: safe placeholder (no external tools required)
//   - AutoDetectExecutor: automatically detects opencode, claude, grok, agy, or codex
//     in $PATH and runs the task using the first available binary.
type Executor interface {
	Execute(ctx context.Context, req ExecutionRequest) (ExecutionResult, error)
}

// StubExecutor is a safe no-op implementation used when no real executor is wired.
// It produces a minimal but well-formed report so the rest of the flow can be exercised.
type StubExecutor struct {
	uploadsDir string
}

func NewStubExecutor(uploadsDir string) *StubExecutor {
	if uploadsDir == "" {
		uploadsDir = os.Getenv("UPLOADS_DIR")
	}
	return &StubExecutor{uploadsDir: uploadsDir}
}

func (e *StubExecutor) Execute(ctx context.Context, req ExecutionRequest) (ExecutionResult, error) {
	hash := req.VisiblePixelHash
	if hash == "" {
		hash = req.ContractID
	}
	if hash == "" {
		hash = "unknown"
	}

	workdir := req.Workdir
	if workdir == "" {
		workdir = filepath.Join(e.uploadsDir, "results", hash)
	}
	if err := os.MkdirAll(workdir, 0755); err != nil {
		return ExecutionResult{}, fmt.Errorf("failed to create workdir: %w", err)
	}

	resultFilename := req.TaskID + ".md"
	if resultFilename == ".md" {
		resultFilename = fmt.Sprintf("task-%d.md", time.Now().Unix())
	}
	resultPath := filepath.Join(workdir, resultFilename)
	publicURL := fmt.Sprintf("/uploads/results/%s/%s", hash, resultFilename)

	statusLine := "Implementation Complete (stub)"
	if req.RejectionFeedback != "" {
		statusLine = "Rework Applied (stub)"
	}

	notes := fmt.Sprintf(`# Task Report: %s

**Agent:** %s
**Task ID:** %s
**Contract:** %s

## Implementation
**Status:** %s

**Description:** %s

### Stub Notes
This is a placeholder result generated by Stargate's built-in agent stub executor.
Real implementation requires wiring an Executor that can invoke an LLM / opencode runner.

`, req.Title, "stargate-builtin", req.TaskID, req.ContractID, statusLine, req.Description)

	if req.RejectionFeedback != "" {
		notes += fmt.Sprintf("\n**Rework Note:** Addressed feedback: %s\n", req.RejectionFeedback)
	}
	if req.ProposalContext != "" {
		notes += "\n**Proposal Context:** Was considered (stub).\n"
	}

	if err := os.WriteFile(resultPath, []byte(notes), 0644); err != nil {
		return ExecutionResult{}, fmt.Errorf("failed to write stub report: %w", err)
	}

	// Ensure a basic index.html exists (mirrors Python worker behavior)
	indexPath := filepath.Join(workdir, "index.html")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		content := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
	<title>Project Results - %s</title>
	<style>
		body { font-family: sans-serif; margin: 2em; line-height: 1.6; max-width: 800px; margin: auto; padding: 2em; background: #f4f7f6; }
		.container { background: white; padding: 2em; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
		h1 { color: #2c3e50; }
	</style>
</head>
<body>
	<div class="container">
		<h1>Project: %s</h1>
		<p>This project was generated by the Stargate built-in agent (stub executor).</p>
		<p>Report: <a href="%s">%s</a></p>
	</div>
</body>
</html>`, hash, hash, publicURL, resultFilename)
		_ = os.WriteFile(indexPath, []byte(content), 0644)
	}

	return ExecutionResult{
		Notes:           notes,
		ResultFile:      publicURL,
		ArtifactsDir:    fmt.Sprintf("/uploads/results/%s/", hash),
		CompletionProof: fmt.Sprintf("stub-%d", time.Now().UnixNano()),
	}, nil
}

// ensureIndexHTML is a small helper in case callers want to force it.
func ensureIndexHTML(dir, visibleHash string) {
	indexPath := filepath.Join(dir, "index.html")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		content := fmt.Sprintf(`<!DOCTYPE html>
<html><head><title>%s</title></head><body><h1>%s</h1><p>Stargate agent placeholder</p></body></html>`,
			html.EscapeString(visibleHash), html.EscapeString(visibleHash))
		_ = os.WriteFile(indexPath, []byte(content), 0644)
	}
}

// ===================== Auto-detecting real Executor =====================

// supportedTools lists the binaries we know how to drive, in priority order.
var supportedTools = []string{"opencode", "claude", "grok", "agy", "codex"}

// AutoDetectExecutor automatically finds a supported AI coding assistant
// (opencode, grok, agy, codex, claude) in the user's PATH and uses it
// to perform the actual work described in the ExecutionRequest.
//
// Detection order: opencode → claude → grok → agy → codex
// You can force a specific one with STARGATE_AGENT_EXECUTOR=claude (etc).
//
// It runs the detected binary inside the task's workdir so that the tool
// can create/edit files directly (like the original Python opencode flow).
type AutoDetectExecutor struct {
	uploadsDir     string
	detectedBinary string // full path or name
	detectedName   string // e.g. "opencode"
}

func NewAutoDetectExecutor(uploadsDir string) *AutoDetectExecutor {
	if uploadsDir == "" {
		uploadsDir = os.Getenv("UPLOADS_DIR")
	}
	e := &AutoDetectExecutor{uploadsDir: uploadsDir}
	e.detect()
	return e
}

func (e *AutoDetectExecutor) detect() {
	// Allow forcing a specific tool via environment variable
	if forced := os.Getenv("STARGATE_AGENT_EXECUTOR"); forced != "" {
		if p, err := exec.LookPath(forced); err == nil {
			e.detectedName = forced
			e.detectedBinary = p
			log.Printf("agents/executor: using forced executor %s at %s (from STARGATE_AGENT_EXECUTOR)", forced, p)
			return
		}
		log.Printf("agents/executor: STARGATE_AGENT_EXECUTOR=%s not found in PATH, falling back to auto-detect", forced)
	}

	for _, name := range supportedTools {
		if p, err := exec.LookPath(name); err == nil {
			e.detectedName = name
			e.detectedBinary = p
			log.Printf("agents/executor: auto-detected %s at %s", name, p)
			return
		}
	}
	log.Printf("agents/executor: no supported AI coding tool found in PATH. Tried: %v. Falling back to stub behavior.", supportedTools)
}

func (e *AutoDetectExecutor) IsAvailable() bool {
	return e.detectedBinary != ""
}

// Execute builds a rich task prompt (matching the style used by the original
// Python agents) and invokes the detected binary.
func (e *AutoDetectExecutor) Execute(ctx context.Context, req ExecutionRequest) (ExecutionResult, error) {
	if !e.IsAvailable() {
		// Graceful fallback so the rest of the agent loop keeps working
		stub := NewStubExecutor(e.uploadsDir)
		return stub.Execute(ctx, req)
	}

	hash := req.VisiblePixelHash
	if hash == "" {
		hash = req.ContractID
	}
	if hash == "" {
		hash = "unknown"
	}

	workdir := req.Workdir
	if workdir == "" {
		workdir = filepath.Join(e.uploadsDir, "results", hash)
	}
	if err := os.MkdirAll(workdir, 0755); err != nil {
		return ExecutionResult{}, fmt.Errorf("failed to create workdir: %w", err)
	}

	// Build the prompt the same way the original Python Worker did
	prompt := e.buildPrompt(req)

	// Run the tool (with context timeout support)
	output, runErr := e.invokeTool(ctx, prompt, workdir)

	// Always try to produce a report file + index.html even if the tool partially succeeded
	resultFilename := req.TaskID + ".md"
	resultPath := filepath.Join(workdir, resultFilename)
	publicURL := fmt.Sprintf("/uploads/results/%s/%s", hash, resultFilename)

	notes := fmt.Sprintf(`# Task Report: %s

**Agent:** %s (via %s)
**Task ID:** %s
**Contract:** %s

## Implementation
**Description:** %s

### Tool Output (%s)
%s
`, req.Title, "stargate-builtin-agent", e.detectedName, req.TaskID, req.ContractID, req.Description, e.detectedName, output)

	if req.RejectionFeedback != "" {
		notes += fmt.Sprintf("\n**Rework Note:** Addressed feedback: %s\n", req.RejectionFeedback)
	}
	if req.ProposalContext != "" {
		notes += fmt.Sprintf("\n**Proposal Context:** %s\n", req.ProposalContext)
	}

	if writeErr := os.WriteFile(resultPath, []byte(notes), 0644); writeErr != nil {
		log.Printf("agents/executor: failed to write report: %v", writeErr)
	}

	// Make sure we have a usable index.html
	e.ensureFrontend(workdir, hash, publicURL, resultFilename)

	res := ExecutionResult{
		Notes:           notes,
		ResultFile:      publicURL,
		ArtifactsDir:    fmt.Sprintf("/uploads/results/%s/", hash),
		CompletionProof: fmt.Sprintf("%s-%d", e.detectedName, time.Now().UnixNano()),
	}

	if runErr != nil {
		return res, fmt.Errorf("%s execution error: %w", e.detectedName, runErr)
	}
	return res, nil
}

func (e *AutoDetectExecutor) buildPrompt(req ExecutionRequest) string {
	skillsStr := "general engineering"

	baseInstruction := fmt.Sprintf(`You are a practical engineer implementing: '%s'.
Skills: [%s].

IMPORTANT: Read AGENTS.md in your current directory for complete working guidelines!

TASK: Complete this work efficiently and provide concrete results.

REQUIREMENTS:
1. Provide specific implementation details
2. Include actual code examples or execution steps
3. Show evidence of completion
4. Keep response concise and actionable
5. COMPLETE PROJECT: Always include an 'index.html' with navigation to provide a complete frontend for your project.
6. PERSISTENT MEMORY: Use 'memory.md' to maintain state, context, and important decisions across multiple tasks for this contract. Review it at the start of each task and update it with significant changes.

Follow security guidelines in AGENTS.md - only allowed imports and operations.
Focus on delivering working solutions, not theoretical discussions.
`, req.Description, skillsStr)

	workType := "NEW WORK"
	if req.RejectionFeedback != "" {
		workType = "REWORK"
	}

	var prompt string
	switch {
	case req.RejectionFeedback != "" && req.PreviousWork != "":
		prompt = fmt.Sprintf(`REWORK REQUIRED - Previous submission was REJECTED.
PREVIOUS WORK: %s
REJECTION FEEDBACK: '%s'
FULL PROPOSAL CONTEXT: %s

%s
`, req.PreviousWork, req.RejectionFeedback, req.ProposalContext, baseInstruction)
	case req.PreviousWork != "":
		prompt = fmt.Sprintf(`CONTINUATION WORK - Based on previous submission.
PREVIOUS WORK: %s
PROPOSAL CONTEXT: %s

%s
`, req.PreviousWork, req.ProposalContext, baseInstruction)
	case req.RejectionFeedback != "":
		prompt = fmt.Sprintf(`REWORK REQUIRED: Your submission for '%s' was REJECTED.
FEEDBACK: '%s'.
PROPOSAL CONTEXT: %s

%s
`, req.Title, req.RejectionFeedback, req.ProposalContext, baseInstruction)
	case req.ProposalContext != "":
		prompt = fmt.Sprintf(`NEW WORK - Full proposal context provided.
PROPOSAL CONTEXT: %s

%s
`, req.ProposalContext, baseInstruction)
	default:
		prompt = baseInstruction
	}

	// Add a little header so the model knows the context
	prompt = fmt.Sprintf("=== %s ===\n\n%s", workType, prompt)
	return prompt
}

// invokeTool runs the detected binary with the prompt in the given workdir.
func (e *AutoDetectExecutor) invokeTool(ctx context.Context, prompt, workdir string) (string, error) {
	var args []string

	switch e.detectedName {
	case "opencode":
		// opencode run "prompt"
		args = []string{"run", prompt}
	case "claude":
		args = []string{prompt}
	case "grok":
		// Grok Build TUI headless single-turn: grok -p "prompt" [--cwd ...]
		// Use -p / --single for non-interactive output to stdout.
		args = []string{"-p", prompt, "--cwd", workdir, "--no-wait-for-background", "--output-format", "plain"}
	case "agy":
		args = []string{"--prompt", prompt}
	case "codex":
		args = []string{prompt}
	default:
		args = []string{prompt}
	}

	// For tools that don't take --cwd in the arg list above, we still set Dir.
	// For grok we already passed it explicitly.
	cmd := exec.CommandContext(ctx, e.detectedBinary, args...)

	// Always set working directory on the command
	cmd.Dir = workdir

	// Pass environment hints
	cmd.Env = append(os.Environ(),
		"AGENT_WORKDIR="+workdir,
		"WORK_DIR="+workdir,
	)

	log.Printf("agents/executor: running %s in %s", e.detectedName, workdir)

	out, err := cmd.CombinedOutput()
	return string(out), err
}

func (e *AutoDetectExecutor) ensureFrontend(workdir, hash, publicURL, resultFilename string) {
	indexPath := filepath.Join(workdir, "index.html")
	if _, err := os.Stat(indexPath); err == nil {
		return
	}

	content := fmt.Sprintf(`<!DOCTYPE html>
<html>
<head>
	<title>Project Results - %s</title>
	<style>
		body { font-family: sans-serif; margin: 2em; line-height: 1.6; max-width: 800px; margin: auto; padding: 2em; background: #f4f7f6; }
		.container { background: white; padding: 2em; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
		h1 { color: #2c3e50; }
	</style>
</head>
<body>
	<div class="container">
		<h1>Project: %s</h1>
		<p>This project was executed by Stargate built-in agent using <strong>%s</strong>.</p>
		<p>Report: <a href="%s">%s</a></p>
	</div>
</body>
</html>`, hash, hash, e.detectedName, publicURL, resultFilename)

	_ = os.WriteFile(indexPath, []byte(content), 0644)
}
